server:
  port: 8802
spring:
  application:
    name: microservice-consumer-movie-feign-hystrix-fallback-stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/
hystrisfeign:
  hystrix:
    enabled: true
feign:
  hystrix:
    enabled: true