spring:
  application:
    name: microservice-discovery-eureka-ha

---
spring:
  profiles: peer1
server:
  port: 8671
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8672/eureka

---
spring:
  profiles: peer2
server:
  port: 8672
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8671/eureka
