server:
  port: 8801
spring:
  application:
    name: microservice-consumer-movie-feign-hystrix-fallback
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/
feign:
  hystrix:
    enabled: true