server:
  port: 8100
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YauChiwei/teecon-spring-cloud-config-repo
          username:
          password: