server:
  port: 8600
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: 'create'
#      ddl-auto: 'create-drop'
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: microservice-provider-user
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8671/eureka
  instance:
    prefer-ip-address: true